name: "BMS Tian/Revov/EG4 Lifepower4"
description: "Tian/Revov BMS Interface"
version: "0.1.0"
slug: "bms_eg4"
url: ""
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

uart: true
usb: true

options:
  mqtt_host: "192.168.10.1"
  mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_password: "mqtt"
  mqtt_ha_discovery: false
  mqtt_ha_discovery_topic: "homeassistant"
  mqtt_base_topic: "bms_lifepower4"
  connection_type: "IP"
  bms_ip: "192.168.10.218"
  bms_port: 8002
  bms_serial: "/dev/ttyUSB0"
  pack_ids: [2,3]
  scan_interval: 1
  debug_output: 1
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_ha_discovery: bool
  mqtt_ha_discovery_topic: str
  mqtt_base_topic: str
  connection_type: list(IP|Serial)
  bms_ip: str
  bms_port: int
  bms_serial: str
  pack_ids: list[int,int]
  scan_interval: int
  debug_output: int